namespace Harmony.Domain.Interfaces.Repositories;

/// <summary>
/// A DM channel as seen by one user: the channel id, the peer on the other side, and
/// the caller's last-read marker. Built for the DM list — one peer per 1:1 channel.
/// </summary>
public record DmChannelView(long ChannelId, long PeerId, long LastReadId, bool IsHidden);

public interface IDirectMessageRepository
{
    /// <summary>The existing 1:1 DM channel shared by two users, or null if none exists.</summary>
    Task<long?> GetSharedChannelIdAsync(long userA, long userB);

    /// <summary>
    /// Creates a DM: a guild-less Channel (type "dm") plus a DirectMessageChannel row per
    /// participant, in one save. The channel id is generated by the caller (snowflake).
    /// </summary>
    Task CreateAsync(long channelId, long userA, long userB, long createdAt);

    Task<bool> IsParticipantAsync(long channelId, long userId);

    Task<List<long>> GetParticipantIdsAsync(long channelId);

    /// <summary>The caller's non-hidden DM channels, each with its peer and last-read marker.</summary>
    Task<List<DmChannelView>> GetVisibleForUserAsync(long userId);

    /// <summary>Hides or unhides a single user's view of a DM channel.</summary>
    Task SetHiddenAsync(long channelId, long userId, bool hidden);

    /// <summary>Clears the hidden flag for every participant — a new message resurfaces the DM.</summary>
    Task UnhideAllAsync(long channelId);
}
