namespace Harmony.Domain.Interfaces.Repositories;

/// <summary>
/// A DM channel from one user's perspective: the channel id, its type ("dm" 1:1 or
/// "group_dm"), the group name (empty for 1:1), the group icon key (null for 1:1 or when
/// unset), and the caller's last-read marker. Participant identity is resolved separately
/// so this stays one row per channel.
/// </summary>
public record DmChannelSummary(long ChannelId, string Type, string Name, string? IconKey, long LastReadId);

public interface IDirectMessageRepository
{
    /// <summary>The existing 1:1 DM channel shared by two users, or null if none exists.</summary>
    Task<long?> GetSharedChannelIdAsync(long userA, long userB);

    /// <summary>
    /// Creates a 1:1 DM: a guild-less Channel (type "dm") plus a DirectMessageChannel row per
    /// participant, in one save. The channel id is generated by the caller (snowflake).
    /// </summary>
    Task CreateAsync(long channelId, long userA, long userB, long createdAt);

    /// <summary>
    /// Creates a group DM: a guild-less Channel (type "group_dm", carrying the group name) plus
    /// a DirectMessageChannel row for each participant (creator included). One save.
    /// </summary>
    Task CreateGroupAsync(
        long channelId,
        string name,
        IReadOnlyList<long> participantIds,
        long createdAt
    );

    Task<bool> IsParticipantAsync(long channelId, long userId);

    Task<List<long>> GetParticipantIdsAsync(long channelId);

    /// <summary>The caller's non-hidden DM/group channels, one summary row each.</summary>
    Task<List<DmChannelSummary>> GetVisibleForUserAsync(long userId);

    /// <summary>
    /// All participant ids for each of the given channels (caller included), keyed by channel id.
    /// One query — no N+1 across the DM list.
    /// </summary>
    Task<Dictionary<long, List<long>>> GetParticipantsForChannelsAsync(IEnumerable<long> channelIds);

    /// <summary>Adds a participant to a group DM (idempotent; visible, last-read 0).</summary>
    Task AddParticipantAsync(long channelId, long userId);

    /// <summary>Removes a participant from a group DM (their "leave"; idempotent).</summary>
    Task RemoveParticipantAsync(long channelId, long userId);

    /// <summary>Hides or unhides a single user's view of a DM channel.</summary>
    Task SetHiddenAsync(long channelId, long userId, bool hidden);

    /// <summary>Clears the hidden flag for every participant — a new message resurfaces the DM.</summary>
    Task UnhideAllAsync(long channelId);
}
